sudo: required
dist: xenial
language: python
git:
  depth: 10
  quiet: true
python:
  - "2.7"
  - "3.6"
env:
  global:
    - TF_LATEST="1.12.*"
    - CODECOV_TOKEN="0d2c482b-f42c-4d4c-b092-cb628ad20857"
    - BAZEL_VERSION=0.20.0
  matrix:
    # We test against recent versions of TensorFlow and tf-nightly.
    # If updating, also update TF_LATEST above
    # TODO: Enable recent versions on release
    - TF_VERSION="1.9.*"
    - TF_VERSION="1.10.*"
    - TF_VERSION="1.11.*"
    - TF_VERSION="1.12.*"
    - TF_VERSION="tf-nightly"
before_install:
  - cat /etc/hosts
  - echo "127.0.0.1 localhost" | sudo tee -a /etc/hosts
  - echo "::1 localhost ip6-localhost ip6-loopback" | sudo tee -a /etc/hosts
  - sudo apt-get -y install pkg-config zip g++ zlib1g-dev unzip
  - wget https://github.com/bazelbuild/bazel/releases/download/"$BAZEL_VERSION"/bazel-"$BAZEL_VERSION"-installer-linux-x86_64.sh
  - chmod +x bazel-"$BAZEL_VERSION"-installer-linux-x86_64.sh
  - ./bazel-"$BAZEL_VERSION"-installer-linux-x86_64.sh --user
  # - sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
  # - sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
  - ip addr # for confirmation. can be skipped
addons:
  apt:
    update: true
install:
  - pip install -r requirements.txt
  - pip install numpy --upgrade
  - ./oss_scripts/oss_pip_install.sh
script:
  - cat /etc/hosts
  - nosetests adanet/core/estimator_distributed_test.py
after_success:
  # Install codecov for tracking coverage over time.
  - pip install codecov
  - codecov
after_failure:
  - cat /tmp/absl_testing/**/*.txt
