sudo: required
language: python
git:
  depth: 10
  quiet: true
python:
  - "2.7"
  - "3.6"
env:
  global:
    - TF_LATEST="1.10.*"
  matrix:
    # We test against recent versions of TensorFlow and tf-nightly.
    # If updating, also update TF_LATEST above
    # TODO(rsepassi): Enable recent versions on release
    # - TF_VERSION="1.9.*"
    # - TF_VERSION="1.10.*"
    - TF_VERSION="tf-nightly"
install:
  - ./oss_scripts/oss_pip_install.sh
script:
  # TODO(weill): Add //adanet/core:estimator_test.
  # Currently it is causing continuous integration to timeout.
  - bazel test -c opt bazel test -c opt //adanet:adanet_test //adanet/core:candidate_test //adanet/core:ensemble_test //adanet/core:evaluator_test //adanet/core:freezer_test //adanet/core:input_utils_test //adanet/core:iteration_test //adanet/core:report_accessor_test //adanet/core:report_materializer_test //adanet/core:summary_test //adanet/core:timer_test //adanet/core/subnetwork/... //adanet/examples/...
