sudo: required
language: python
git:
  depth: 10
  quiet: true
python:
  - "2.7"
  - "3.6"
env:
  global:
    - TF_LATEST="1.12.*"
  matrix:
    # We test against recent versions of TensorFlow and tf-nightly.
    # If updating, also update TF_LATEST above
    # TODO: Enable recent versions on release
    - TF_VERSION="1.9.*"
    - TF_VERSION="1.10.*"
    - TF_VERSION="1.11.*"
    - TF_VERSION="1.12.*"
    - TF_VERSION="tf-nightly"
install:
  - ./oss_scripts/oss_pip_install.sh
script:
  - bazel test -c opt //... --test_output=errors
