# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  default_test_job: &default_test_job

    docker:
      - image: circleci/python:3.6

    working_directory: ~/adanet

    environment:
      TF_LATEST: "1.12.*"
      CODECOV_TOKEN: 0d2c482b-f42c-4d4c-b092-cb628ad20857

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            ./oss_scripts/oss_pip_install.sh
            sudo pip install -r requirements.txt

      - save_cache:
          paths:
            - /usr/local/lib/python3.6/site-packages/
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            nosetests

      - run:
          name: upload coverage
          command: coverage
          when: on_success

      - run:
          name: test pip install adanet
          command: |
            # Create the adanet pip package
            bazel-bin/adanet/pip_package/build_pip_package /tmp/adanet_pkg

            # Install and test the pip package
            pip install /tmp/adanet_pkg/*.whl --user

            # Finally try importing `adanet` in Python outside the cloned directory:
            cd ..
            python -c "import adanet"
            cd adanet

      - store_artifacts:
          path: /tmp/absl_testing/*.txt
          destination: /tmp/absl_testing

  build_and_test_2_7_tf_1_9:
    <<: *default_test_job
    docker:
      - image: circleci/python:2.7.14

    environment:
      TF_VERSION: "1.9.*"

  build_and_test_3_6_tf_1_9:
    <<: *default_test_job
    docker:
      - image: circleci/python:3.6.4

    environment:
      TF_VERSION: "1.9.*"

  build_and_test_2_7_tf_1_10:
    <<: *default_test_job
    docker:
      - image: circleci/python:2.7.14

    environment:
      TF_VERSION: "1.10.*"

  build_and_test_3_6_tf_1_10:
    <<: *default_test_job
    docker:
      - image: circleci/python:3.6.4

    environment:
      TF_VERSION: "1.10.*"

  build_and_test_2_7_tf_1_11:
    <<: *default_test_job
    docker:
      - image: circleci/python:2.7.14

    environment:
      TF_VERSION: "1.11.*"

  build_and_test_3_6_tf_1_11:
    <<: *default_test_job
    docker:
      - image: circleci/python:3.6.4

    environment:
      TF_VERSION: "1.11.*"

  build_and_test_2_7_tf_1_12:
    <<: *default_test_job
    docker:
      - image: circleci/python:2.7.14

    environment:
      TF_VERSION: "1.12.*"

  build_and_test_3_6_tf_1_12:
    <<: *default_test_job
    docker:
      - image: circleci/python:3.6.4

    environment:
      TF_VERSION: "1.12.*"

  build_and_test_2_7_tf_nightly:
    <<: *default_test_job
    docker:
      - image: circleci/python:2.7.14

    environment:
      TF_VERSION: tf-nightly

  build_and_test_3_6_tf_nightly:
    <<: *default_test_job
    docker:
      - image: circleci/python:3.6.4

    environment:
      TF_VERSION: tf-nightly

workflows:
  version: 2
  build_test:
    jobs:
      - build_and_test_2_7_tf_1_9
      - build_and_test_3_6_tf_1_9
      - build_and_test_2_7_tf_1_10
      - build_and_test_3_6_tf_1_10
      - build_and_test_2_7_tf_1_11
      - build_and_test_3_6_tf_1_11
      - build_and_test_2_7_tf_1_12
      - build_and_test_3_6_tf_1_12
      - build_and_test_2_7_tf_nightly
      - build_and_test_3_6_tf_nightly
